version: '3.5'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.12
    volumes:
      - ./mosquitto-config:/mosquitto/config:ro
      - ./mosquitto-config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto-config/passwd:/mosquitto/passwd:ro
      - ./certs:/mosquitto/certs:rw
      - ./log:/mosquitto/log:rw
    ports:
      - '1883:1883'
    restart: "no"
